spring.application.name=kjgl0001

mybatis.type-aliases-package=com.ite.kjgl0001.pojo
mybatis.mapper-locations=classpath:mapper/*.xml

spring.datasource.username=root
spring.datasource.password=200592311zxm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/kjgl001?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
server.port=8080


mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

logging.level.com.ite.classprojectforspringboot.Mapper=DEBUG

spring.devtools.restart.enabled=true
